title: TRINITY COLLEGE OF ENGINEERING AND TECHNOLOGY
logo: /assets/img/abhishek.jpg
description: East or West, Friendship is the best...
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
